package:
  name: bayeslite
  version: {{ CONDA_PACKAGE_VERSION }}

source:
  path: ../

build:
  script: python setup.py install

requirements:
  build:
    - git
    - python 2.7.*
    - cython >=0.20.1
    - jsonschema
    - numpy 1.8.*
  run:
    - jsonschema
    - numpy 1.8.*
    - scipy >=0.11.0
    - six

test:
  requires:
    - python 2.7.*
    - pytest 2.5.1.*
  commands:
    - python -m pytest --pyargs bayeslite

about:
  home: https://github.com/probcomp/bayeslite
  license: Apache
  license_file: LICENSE.txt
